### ISSUE TITLE
企画ミーティング

### ISSUE THREAD

**Issue by youryota** [youryota/shooting_game#11]

**Comment by kikuchihibiki** [comment]
**使用言語**
* javascrpt 
**必須機能**
* スクロールなしのシューティング
* 的の数数体
* スコア表示
* スコア上限でクリア
* 基本操作　スペースで発砲　矢印で移動
* タイトルにスタートボタン
* 制限時間はなし
* ゲーム終了したのちスタートボタンに戻る
* 敵がランダムで出現し当たるとライフを消費
* 3ライフなくなるとゲームオーバー

**Comment by youryota** [comment]
### 操作方法
- 矢印キーで上下左右に移動
- スペースキーで弾を発射
### 敵
- 動かない敵と動く敵
- 動く敵はプレイヤーにぶつかってくる
- 動かない敵は四方八方に弾を飛ばしてくる

**Comment by kikuchihibiki** [comment]
使用言語

javascrpt
必須機能
スクロールなしのシューティング
的の数数体
スコア表示
スコア上限でクリア
基本操作　スペースで発砲　矢印で移動
タイトルにスタートボタン
制限時間はなし
ゲーム終了したのちスタートボタンに戻る
敵がランダムで出現し当たるとライフを消費
3ライフなくなるとゲームオーバー
操作方法
矢印キーで上下左右に移動
スペースキーで弾を発射
敵
動かない敵と動く敵
動く敵はプレイヤーにぶつかってくる
動かない敵は四方八方に弾を飛ばしてくる

**Comment by kikuchihibiki** [comment]
作ってい見て状況で考える
